[disable_multiStonk]
# DISABLING THIS TO USE THE MAIN REPO: https://github.com/steveman1123/multiStonk/tree/main
disable_multistonk = true

[use_broker]
Robinhood = true
Gasty = false


[robinhood_login]
# ROBINHOOD LOGIN:
username = ""
password = ""
mfa_code = "totp"
TOTPS = ""


[alpaca_login]
# ALPACA LOGIN REQUIRED:
"ALPACAPAPERKEY" = ""
"ALPACAPAPERSECRETKEY" = ""
"ALPACAPAPERURL"= "https://paper-api.alpaca.markets"



[order_limit]
# ORDER LIMIT is required for the following don't change the values. 
# ORDER LIMIT:
use_order_limit = true
place_limitOders = true
remove_fees = true
market_order = true
remove_fee = 0.0000051
buy_limit = 0.00021
sell_limit = 0.00021


[database_settings]
# DATABASE SETTINGS:
mongodb_url = "mongodb://127.0.0.1:27017/?readPreference=primary&serverSelectionTimeoutMS=2000&appname=MongoDB%20Compass&directConnection=true&ssl=false"

[news_sources]
# NEWS SOURCES:
BING_SEARCH = "https://www.bing.com/news/search?q="





#location of various files
[file_locations]

# stockDataDir = './stockStuff/stockData/robinhood_cvs/'

#location of the algorithm files for stocks

news_file = './Users/admin/multiStonk/stockStuff/market_sentiment/stock_news.json'
stockAlgosDir = './algos/'
user_stockAlgosDir = './user_algorithms/'
stockDataDir = './stockStuff/stockData/'


#where the currently held stocks are stored and various info about them, as well as the cash returned by
posList = './stockStuff/posListMulti.json'

#file containing the stocks to buy for the day
buyList = './stockStuff/buyListMulti.json'

#where the API keys are stored
keyFile = 'robinhood_config.toml'

#file containing the error tracebacks
errLog = './stockStuff/multiStonkErr.txt'


#parameters related to the entire account/portfolio
[account_params]

#determine whether paper trading or live trading should be used (1=paper, 0=live)
isPaper = 1

#stop trading/sell everything if the portfolio is <= maxPortValue*this
portStopLoss = 0.95

#if the portfolio does drop below the stopLoss above, selling everything can be done manually or automatically.
#1 = automatically sell everything
#0 = require user confirmation to sell everything
portAutoSellOff = 1

#cash withholding params:
#minimum cash (in $) to hang on to and not trade (if total cash is ever > than this)
minCash2hold = 15000

#extra cash to hold onto beyond the minimum. THIS MUST BE >=1
minCashMargin = 1.1

#(% of maxPortVal) if maxPortVal*this > minCash*minCashMargin, then keep that much cash to hold
maxCash2hold = 0.2

#minimum cash to throw at a stock (eg. if a list has $25 available to it, and has 100 stocks to choose from, do not put only $0.25/stock, bottom out at this number)
minDolPerStock = 5

#max % of volume we should buy (0.01=1% = 0.01*volume)
maxVolPerc = 0.005



#parameters relating to when things should happen
[time_params]

#start buying this many minutes before close
buyTime = 15

#update the stock lists this many minutes before market opens
updateLists = 180


#######################
# Start algo settings #
#######################

#settings that apply to all algos
[allAlgos]
#list of algos that the progam should use (should be identical to the file names as those in algosDir)
# algoList = ['dj', 'fda', 'fda3']
algoList = ['dj']





[divs]
#max share price to look at
maxPrice = 60
#min share price to look at
minPrice = 2
#min stock volume to look for
minVol = 20000
#max time to allow for a div to execute (in days)
maxTime = 20
#minimum amount (in $) for a div to be
minDiv = 0.05
#min (appx) div/buyPrice value
minDivYield = 0.007
#maximum number of symbols to allow per day (too many can cause no purchases to be made
maxSymbs = 15



#trigger if it reaches this gain % before the pmt dividend date
preSellUp = 1.2
#sell the stock if it falls to this loss % before the pmt dividend date
preSellDn = 0.93
#trigger if it reaches this gain % after the pmt dividend date
postSellUp = 1.04
#sell the stock if it falls to this loss % after the pmt dividend date
postSellDn = 0.96
#after the trigger point, sell if it drops to this much
sellUpDn = 0.99



#double jump parameters
[dj]
#trigger if it reaches this gain %
sellUp = 1.19
#sell the stock if it falls to this loss %
sellDn = 0.75
#after the trigger point, sell if it drops to this much
sellUpDn = 0.98

#number of weeks to wait until starting to squeeze (reducing sellUp and increasing sellDn)
startSqueeze = 4

#number of weeks after startSqueeze weeks to squeeze to a 0% P/L
squeezeTime = 4

#min price to look at (in USD)
simMinPrice = 0.8
#max price to look at (in USD)
simMaxPrice = 5
#min daily volume to look at
simMinVol = 300000

#days to look for the first jump
simDays2look = 25
#days to wait for the fall of that jump
simWait4fall = 3
#offset that next jump by this many days
simStartDateDiff = 1
#first jump must be at least this much
simFirstJumpAmt = 1.3
#sell if the historical value jumps by this amount in a day
simSellUp = 1.2
#sell if the historical value falls by this amount in a day
simSellDn = 0.5
#average the volume for this many days
simVolAvgDays = 60
#check if the price jumped substantially over the last __ trade days
simChkPriceDays = 30
#check if the price jumped by this much in that last <simChkPriceDays> days
simChkPriceAmt = 1.7
#check that the volume gained this many times over the average during the jump
simVolGain = 3
#check that the volume fell by this much after the jump
simVolLoss = 0.5
#check that the price dropped this much after the jump
simPriceDrop = 0.4



[earn]
#max share price to look at
maxPrice = 15
#min share price to look at
minPrice = 3

#weight to give to the history check (increasing over time) (1=equal footing as the others,0=do not consider)
histWeight = 0.75
#minimum confidence to have in the calculations to be considered a good buy (0=no confidence, 1=perfectly confident)
minConf = 0.4
#minimum expectations to be considered a good buy (-1=abysmal expecations, 1=insanely high expectations
minExpec = 0.3

#trigger if it reaches this gain %
sellUp = 1.21
#adjust the tgtPrice/BuyPrice ratio to give larger gains (eg if tgt/buy=1.1 and this is 1.5, then sellUp=1.15)
sellUpAdjustment = 1.2
#after the trigger point, sell if it drops to this much
sellUpDn = 0.98
#sell the stock if it falls to this loss %
sellDn = 0.8
#set the sellDn to be this % of sellUp (eg if sellUp is 1.2 and this is 0.25, then sellDn=0.95)
sellDnPerc = 0.5


[ema]
#max share price to look at
maxPrice = 15
#min share price to look at
minPrice = 3
#min stock volume to look at
minVol = 250000
#trigger if it reaches this gain %
sellUp = 1.5
#after the trigger point, sell if it drops to this much
sellUpDn = 0.98
#sell the stock if it falls to this loss %
sellDn = 0.9

#number of weeks after the second test to start squeezing
startSqueeze = 6
#number of weeks to squeeze to 0% P/L
squeezeTime = 3

#short number of days to average over
emaSper = 8
#long number of days to average over
emaLper = 20
#how many periods to look back for an EMA crossover
timeLim = 20
#number of tests to limit at (usually 2. could potentially go up to 3?)
testNum = 2



[fda]
#max share price to look at
maxPrice = 30
#min share price to look at
minPrice = 2

#trigger if it reaches this gain %
sellUp = 1.5
#after the trigger point, sell if it drops to this much
sellUpDn = 0.95
#sell the stock if it falls to this loss %
sellDn = 0.85



[fda2]
#max share price to look at
maxPrice = 30
#min share price to look at
minPrice = 2

#trigger if it reaches this gain %
sellUp = 1.5
#after the trigger point, sell if it drops to this much
sellUpDn = 0.95
#sell the stock if it falls to this loss %
sellDn = 0.9



[fda3]
#max share price to look at
maxPrice = 60
#min share price to look at
minPrice = 0.8

#trigger if it reaches this gain % before the catalyst date
preSellUp = 1.35
#sell the stock if it falls to this loss % wrt the buyPrice or the open price before the catalyst date
preSellDn = 0.75
#trigger if it reaches this gain % after the catalyst date
postSellUp = 1.5
#sell the stock if it falls to this loss % wrt the buyPrice or the open price afterthe catalyst date
postSellDn = 0.85

#after the trigger point, sell if it drops to this much wrt the max price seen
sellUpDn = 0.97

#number of trading days to perform a simple moving average over
smaDays = 10
#stock must gain this % within the past year (1.3 = 30% gain)
twelveMgain = 1.3
#stock must gain this % within the past 6 months (1.1 = 10% gain)
sixMgain = 1.1



[iped]
sellUp = 1.75
#after the trigger point, sell if it drops to this much wrt the max price seen
sellUpDn = 0.97
#sell the stock if it falls to this loss % wrt the buyPrice or the open price
sellDn = 0.85



[movers]
#max share price to look at
maxPrice = 15
#min share price to look at
minPrice = 3

sellUp = 1.1
#after the trigger point, sell if it drops to this much wrt the max price seen
sellUpDn = 0.98
#sell the stock if it falls to this loss % wrt the buyPrice or the open price
sellDn = 0.8

#use these two params to set the change range
#max gain to consider a good buy
maxGain = 0
#max loss to consider a good buy
maxLoss = -20



[splits]
#number of weeks to compare current price to to see if its gained enough
compWks = 3
#number of days before execution date to look
daysBeforeExec = 10
#max days before execution date that can be considered valid
maxDays = 14








